<a href="https://colab.research.google.com/github/Dhananjay0705/Numpy-Library/blob/main/Advanced_Indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Advanced Indexing**

In [2]:
import numpy as np

In [17]:
## Normal Indexing
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [18]:
a[1,1]

np.int64(5)

In [19]:
## Normal Slicing
a[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [24]:
## Fancy Indexing
a[[0,4,5]] ## 0,4,5 are rows in indexing number
a[:,[2,3]] ## 2,3 are columns in indexing number


array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [29]:
## Boolean Indexing
b = np.random.randint(1,100,24).reshape(6,4)

In [30]:
## Find all numbers greater than 50
b > 50

array([[False,  True,  True,  True],
       [ True, False,  True, False],
       [False,  True, False,  True],
       [False,  True,  True, False],
       [ True, False,  True,  True],
       [ True, False, False,  True]])