<a href="https://colab.research.google.com/github/Dhananjay0705/Numpy-Library/blob/main/array_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**ARRAY FUNCTIONS**

In [1]:
import numpy as np

In [2]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[33., 11., 22.],
       [91., 55., 92.],
       [50.,  7., 60.]])

In [3]:
## max/min/sum/prod
## 0--> col , 1 ---> raws
np.max(a1,axis = 1) ## for rows


array([33., 92., 60.])

In [7]:
## mean/median/std/var
np.mean(a1,axis = 1)
np.median(a1,axis = 1)
np.std(a1,axis = 1)
np.var(a1,axis = 1)

array([ 80.66666667, 296.22222222, 528.66666667])

In [11]:
## trignometric Functions
np.sin(a1)

array([[ 0.99991186, -0.99999021, -0.00885131],
       [ 0.10598751, -0.99975517, -0.77946607],
       [-0.26237485,  0.6569866 , -0.30481062]])

In [14]:
## dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [16]:
## Log & Exponents
np.log(a1)
np.exp(a1)

array([[2.14643580e+14, 5.98741417e+04, 3.58491285e+09],
       [3.31740010e+39, 7.69478527e+23, 9.01762841e+39],
       [5.18470553e+21, 1.09663316e+03, 1.14200739e+26]])

In [21]:
## round/floor/ceil
np.round(np.random.random((2,3))*100)
np.floor(np.random.random((2,3))*100) ## floor use for back roundoff
np.ceil(np.random.random((2,3))*100) ## ceil use for forward next integer


array([[72., 54., 55.],
       [60., 19., 74.]])