<a href="https://colab.research.google.com/github/Dhananjay0705/Numpy-Library/blob/main/Indexing_%26_Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**INDEXING & SLICING**

In [3]:
import numpy as np

In [6]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [7]:
a1[-1] ## last item from thev a1 array

np.int64(9)

In [9]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
a2[1,0]

np.int64(4)

In [17]:
a3 ## its a 3D tensior

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [18]:
a3[1,0,1]

np.int64(5)

In [19]:
a3[0,0,0]

np.int64(0)

**SLICING**

In [21]:
a1[2:5]

array([2, 3, 4])