<a href="https://colab.research.google.com/github/Dhananjay0705/Numpy-Library/blob/main/Indexing_%26_Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**INDEXING & SLICING**

In [29]:
import numpy as np

In [30]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(27).reshape(3,3,3)


In [31]:
a1[-1] ## last item from thev a1 array

np.int64(9)

In [32]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
a2[1,0]

np.int64(4)

In [34]:
a3 ## its a 3D tensior

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [35]:
a3[1,0,1]

np.int64(10)

In [36]:
a3[0,0,0]

np.int64(0)

**SLICING**

In [37]:
a1[2:5]

array([2, 3, 4])

In [38]:
a1[2:5:2]

array([2, 4])

In [39]:
a2[0,:]

array([0, 1, 2, 3])

In [40]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
a2[:,2]

array([ 2,  6, 10])

In [42]:
a2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [43]:
a2[::2,1::2] ## for 0,3,8,11 values

array([[ 1,  3],
       [ 9, 11]])

In [44]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
a2[1,0::3]

array([4, 7])

In [46]:
a2[0:2,1:4]

array([[1, 2, 3],
       [5, 6, 7]])

In [47]:
a2[0:3:2,0:2]

array([[0, 1],
       [8, 9]])

In [48]:
a2[1,1:4:2]

array([5, 7])

In [49]:
a2[2,1:4:2]

array([ 9, 11])

In [50]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [51]:
a3[1] ## for show 2nd block

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [52]:
a3[0:3:2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [53]:
a3[0,1]

array([3, 4, 5])

In [54]:
a3[1,:,1]

array([10, 13, 16])

In [55]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [56]:
a3[0:3:2,0,0:3:2]

array([[ 0,  2],
       [18, 20]])