<a href="https://colab.research.google.com/github/Dhananjay0705/Numpy-Library/blob/main/Indexing_%26_Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**INDEXING & SLICING**

In [1]:
import numpy as np

In [2]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [3]:
a1[-1] ## last item from thev a1 array

np.int64(9)

In [4]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
a2[1,0]

np.int64(4)

In [6]:
a3 ## its a 3D tensior

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [7]:
a3[1,0,1]

np.int64(5)

In [8]:
a3[0,0,0]

np.int64(0)

**SLICING**

In [9]:
a1[2:5]

array([2, 3, 4])

In [10]:
a1[2:5:2]

array([2, 4])

In [12]:
a2[0,:]

array([0, 1, 2, 3])

In [13]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
a2[:,2]

array([ 2,  6, 10])

In [16]:
a2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])