<a href="https://colab.research.google.com/github/Dhananjay0705/Numpy-Library/blob/main/Iterating.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Iterating**

In [14]:
import numpy as np

In [15]:

a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(27).reshape(3,3,3)

In [16]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [17]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [18]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [19]:
for i in np.nditer(a3) :
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


**RESHAPE**

In [20]:
## Transpose
np.transpose(a2) ## transpose the matrix convert rows into columns and columns into rows

##  a2.T is give same output of np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

**Stacking**

In [21]:
## horizontal Stacking ## This is use for merge multiple datasource
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
np.hstack((a4,a5)) ## a4,a5 ko horizontal stack karna

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [23]:
## Vertical Stacking ## This is use for merge multiple datasource
np.vstack((a4,a5))

## the rule for stacking is shape same

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

**Splitting**

In [28]:
## Horizontal Splitting ## This is use for split thr data from the datasource
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
np.hsplit(a4,2) ## It has to be a equal division

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [30]:
## Vertical Splitting ## This is use for split thr data from the datasource
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]