<a href="https://colab.research.google.com/github/Dhananjay0705/Numpy-Library/blob/main/Iterating.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Iterating**

In [1]:
import numpy as np

In [2]:

a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(27).reshape(3,3,3)

In [4]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [5]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [7]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [8]:
for i in np.nditer(a3) :
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


**RESHAPE**

In [13]:
## Transpose
np.transpose(a2) ## transpose the matrix convert rows into columns and columns into rows

##  a2.T is give same output of np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])