<a href="https://colab.research.google.com/github/Dhananjay0705/Numpy-Library/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Creating Numpy Array


In [3]:
import numpy as np
a = np.array([1,2,3])
print(a) ## Result of a is vector
print(type(a)) ## datatype of a

[1 2 3]
<class 'numpy.ndarray'>


In [10]:
## 2D Array
b = np.array([[1,2,3],[4,5,6]])
print(b) ## Result of b is matrix

[[1 2 3]
 [4 5 6]]


In [11]:
# 3D Array
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
print(c.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
