<a href="https://colab.research.google.com/github/Dhananjay0705/Numpy-Library/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Creating Numpy Array


In [1]:
import numpy as np
a = np.array([1,2,3])
print(a) ## Result of a is vector
print(type(a)) ## datatype of a

[1 2 3]
<class 'numpy.ndarray'>


In [2]:
## 2D Array
b = np.array([[1,2,3],[4,5,6]])
print(b) ## Result of b is matrix

[[1 2 3]
 [4 5 6]]


In [3]:
# 3D Array
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c) ## result of c is tensor
print(c.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [4]:
## Dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [5]:
## np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [6]:
## with reshape
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [8]:
##np.ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
## np.zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
## np.random
np.random.random((3,4))

array([[0.89823829, 0.71056107, 0.37658802, 0.01442498],
       [0.5513643 , 0.52087268, 0.65038176, 0.60650876],
       [0.75663965, 0.83347361, 0.9257057 , 0.97800044]])

In [11]:
## np.linspace
np.linspace(-10,10,10)


array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [12]:
## np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])